# a function that raises a name exception with a message


def raise_exception_msg(message=""):
    raise NameError("This is a Name Error")
